FROM openjdk:11-jre-slim
COPY build/libs/employee-performance-service-0.0.1-SNAPSHOT.jar employee-performance-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/employee-performance-service-0.0.1-SNAPSHOT.jar"]